# Generated by Django 6.0.4 on 2026-05-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='price_type',
            field=models.CharField(choices=[('standard', 'Обычная'), ('discount', 'Со скидкой'), ('vip', 'VIP')], default='standard', max_length=20),
        ),
    ]
