# Generated by Django 6.0.5 on 2026-05-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_cake_price_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('apple', 'Яблочный'), ('cherry', 'Вишнёвый'), ('meat', 'Мясной')], max_length=50)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('dough', models.CharField(choices=[('classic', 'Классическое'), ('puff', 'Слоёное'), ('sweet', 'Сдобное')], max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
    ]
